# Generated by Django 5.0.2 on 2024-04-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='postal_code',
            new_name='dist_code',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='country_code',
            new_name='state_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
